# fly.toml app configuration file generated for nwr-website on 2024-10-08T21:22:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nwr-website'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
